name: test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: |
        sudo wget https://github.com/jgm/pandoc/releases/download/3.1.11.1/pandoc-3.1.11.1-1-amd64.deb
        sudo dpkg -i pandoc-3.1.11.1-1-amd64.deb
        rm -f pandoc-3.1.11.1-1-amd64.deb

    - name: build man page
      run: make man

    - name: run tests
      run: make test
